# nginx proxy address - http://172.17.0.1:8098

name: domoticz
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  domoticz:
    image: domoticz/domoticz:latest
    pull_policy: always
    container_name: domoticz-app
    restart: always
    logging: *default-logging
    networks:
      - domoticz
    ports:
      - "172.17.0.1:8098:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./volumes/config/domoticz:/config
      - ./volumes/data/domoticz:/data

networks:
  domoticz:
    name: domoticz
    external: false
